apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.17.2
    helm:
      valuesObject:
        crds:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ghcr.io/akuity/kargo-charts
    chart: kargo
    targetRevision: 1.3.2
    helm:
      valuesObject:
        api:
          adminAccount:
            enabled: true
            passwordHash: $2y$10$1wCK9BN64ZX3foLeKbsQxutFuvfAlYzuU3GngSzJ5a3jwOCQ3WLvG
            tokenSigningKey: iwishtowashmyirishwristwatch
  destination:
    server: https://kubernetes.default.svc
    namespace: kargo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-project-testapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gjhenrique-prezi/kargo-test.git
    targetRevision: master
    path: kargo
  destination:
    server: https://kubernetes.default.svc
    namespace: testapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testapp-preprod
  namespace: argocd
  labels:
    kargo.akuity.io/project: testapp
spec:
  project: default
  source:
    repoURL: https://github.com/gjhenrique-prezi/kargo-test.git
    targetRevision: master
    path: apps/testapp/stages/preprod
  destination:
    server: https://kubernetes.default.svc
    namespace: testapp-preprod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testapp-production
  namespace: argocd
  labels:
    kargo.akuity.io/project: testapp
spec:
  project: default
  source:
    repoURL: https://github.com/gjhenrique-prezi/kargo-test.git
    targetRevision: master
    path: apps/testapp/stages/production
  destination:
    server: https://kubernetes.default.svc
    namespace: testapp-production
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
