apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testapp-preprod
  namespace: argocd
  labels:
    kargo.akuity.io/project: testapp
spec:
  project: default
  source:
    repoURL: https://github.com/gjhenrique-prezi/kargo-test.git
    targetRevision: master
    path: apps/testapp/stages/preprod
  destination:
    server: https://kubernetes.default.svc
    namespace: testapp-preprod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testapp-production
  namespace: argocd
  labels:
    kargo.akuity.io/project: testapp
spec:
  project: default
  source:
    repoURL: https://github.com/gjhenrique-prezi/kargo-test.git
    targetRevision: master
    path: apps/testapp/stages/production
  destination:
    server: https://kubernetes.default.svc
    namespace: testapp-production
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
