apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
        - name: testapp
          image: ghcr.io/gjhenrique-prezi/kargo-test:0.1.0
          ports:
            - containerPort: 80
          env:
            - name: ENV_NAME
              value: dev
            - name: VERSION
              value: "0.1.0"
